### ISSUE TITLE
beforeEach is not defined

### ISSUE THREAD

**Issue by alon24** [mikeborozdin/jest-react-hooks-shallow#19]
I am seeing this error:
```
ReferenceError: beforeEach is not defined
      at Object.mockUseEffect [as default] (node_modules/jest-react-hooks-shallow/lib/mock-use-effect/mock-use-effect.js:10:5)
      at enableHooks (node_modules/jest-react-hooks-shallow/lib/enable-hooks.js:17:67)
      at Object.<anonymous> (config/jest/setup.js:24:39)
```

```import Enzyme from 'enzyme'; // eslint-disable-line import/no-extraneous-dependencies
import Adapter from 'enzyme-adapter-react-16'; // eslint-disable-line import/no-extraneous-dependencies
import jestFetchMock from 'jest-fetch-mock'; // eslint-disable-line import/no-extraneous-dependencies
import 'babel-polyfill'; // eslint-disable-line import/no-extraneous-dependencies
import enableHooks from 'jest-react-hooks-shallow';

global.fetch = jestFetchMock;
global.local = {
  baseurl: "ThisisiAbaseurl"
}

// pass an instance of jest to `enableHooks()`
enableHooks(jest);

Enzyme.configure({ adapter: new Adapter() });

```

```
test('Renders default message and updates it on clicking a button', () => {
  const component = shallow(<GenerateSecretForm />);
});
```

**Comment by mikeborozdin** [comment]
Hi @alon24,

Thanks a lot for reporting the issue!

Are you calling `enableHooks()` in a file that is defined as `setupFilesAfterEnv` or `setupFiles` in your Jest config?

It has to be `setupFilesAfterEnv`. 

It looks similar to the other reported issue, so you may also want to check t[he solution there.](https://github.com/mikeborozdin/jest-react-hooks-shallow/issues/16#issuecomment-632369616)
